manifest_version = 2
name = "Default starter for JavaScript"
description = "A basic starter kit that demonstrates routing, simple synthetic responses and overriding caching rules."
authors = ["<oss@fastly.com>"]
language = "javascript"
service_id = "40TbEWfCHyZp1xTHW7LOu0"
